### ISSUE TITLE
DISCORD_TOKEN = os.getenv("KVR_TOKEN")

### ISSUE THREAD

**Issue by YiranHuangIrene** [naderfyi/kvr_termin_bot#1]
Thanks for your nice script. However, I received a TypeError: The token provided was of type <class 'NoneType'> but was expected to be str, which is caused by the wrong DISCORD_TOKEN. What is the KVR_TOKEN here? thanks!

**Comment by naderfyi** [comment]
The Token is the discord application token. You have to create a new discord app and get the Token for it.
https://www.writebots.com/discord-bot-token/
